global:
    scrape_interval: 30s
    scrape_timeout: 10s

    rule_files:
      - alert.yml

    scrape_configs:
      - job_name: services
        static_configs:
           - targets:
               - 'localhost:9090'
      - job_name: csvserver
        static_configs:
          - targets:
              - '54.250.207.232:9393'
